# build settings in this file
[build]
command = "yarn build"
publish = "dist"
# Cypress plugin
[[plugins]]
package = "netlify-plugin-cypress"
[plugins.inputs]
# run E2E tests against the deployed URL
record = true
group = 'deployed'
[plugins.inputs.postBuild]
# run E2E tests against locally built site
# before deploying it
enable = true
record = true
group = 'built'